module.exports = {
  resLabel: {
    'AgeNum': '年龄',
    'DressLowerColor': '下身颜色',
    'DressLowerStyle': '下身服饰',
    'DressUpperCoat': '是否穿大衣',
    'DressUpperColor': '上身颜色',
    'DressUpperSize': '上身服饰尺寸',
    'Gender': '性别',
    'Orientation': '人朝向',
    'WearHat': '是否戴帽子',
    'HatColor': '帽子颜色',
    'beard': '胡子',
    'expression': '表情',
    'expressionThree': '表情三分类',
    'glasses': '眼镜',
    'hair': '头发',
    // 'attributes': '',
    // 'faceImageUri': '人脸图',
    // 'faceRect': '',
    'face_id': '明星ID',
    // 'humanImageUri': '人体图',
    // 'humanRect': '',
    'name': '姓名',
    'time': '时间',
    'TrackId': '跟踪ID',
    'Blur': '人脸模糊程度',
    'Yaw': '人脸侧偏角度',
    'Pitch': '人脸俯仰角度',
    'PfScore': '检测框置信度',
    'Partial': '人体完整置信度',
    'HumanRect': '人体检测框',
    'HeadRect': '人头检测框',
    'FaceRect': '人脸检测框'
  }
}
